In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./data/data_best_ratings.csv")

In [3]:
df.head()

,Unnamed: 0,imdb_title_id,original_title,year,date_published,genre,duration,country,language,director,actors,description,avg_vote,votes
0,0,tt0017938,La glace à trois faces,1983,1983-03-13,"Drama, Romance",45,France,"None, French",Jean Epstein,"Jeanne Helbling, Suzy Pierson, Olga Day, Raymo...",Psychological narrative avantgarde film about ...,7.0,759
1,1,tt0052205,The Small World of Sammy Lee,1963,1963-04-01,Drama,107,UK,English,Ken Hughes,"Anthony Newley, Julia Foster, Robert Stephens,...",The compère of a seedy strip club struggles to...,7.1,353
2,2,tt0052607,The Battle of the Sexes,1960,1960-08-22,Comedy,84,UK,English,Charles Crichton,"Peter Sellers, Robert Morley, Constance Cummin...","Angela Barrows, an accomplished business analy...",6.7,1188
3,3,tt0052698,Classe tous risques,1960,1960-04-01,"Crime, Drama, Romance",110,"France, Italy","French, Italian",Claude Sautet,"Lino Ventura, Sandra Milo, Jean-Paul Belmondo,...","Abel Davos is a criminal, hunted in Italy. The...",7.5,3116
4,4,tt0052721,Darbuján a Pandrhola,1960,1960-06-10,"Comedy, Fantasy",80,Czechoslovakia,Czech,Martin Fric,"Jirí Sovák, Rudolf Hrusínský, Václav Lohniský,...",Cuba Drobbyan (Jiri Sovak) is a poor cavalier ...,7.4,339

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17572 entries, 0 to 17571
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      17572 non-null  int64
 1   imdb_title_id   17572 non-null  object
 2   original_title  17572 non-null  object
 3   year            17572 non-null  object
 4   date_published  17572 non-null  object
 5   genre           17572 non-null  object
 6   duration        17572 non-null  int64
 7   country         17572 non-null  object
 8   language        17572 non-null  object
 9   director        17572 non-null  object
 10  actors          17572 non-null  object
 11  description     17572 non-null  object
 12  avg_vote        17572 non-null  float64
 13  votes           17572 non-null  int64
dtypes: float64(1), int64(3), object(10)
memory usage: 1.9+ MB

In [9]:
new_df = df[df['year']>"2000"]

In [10]:
new_df

,Unnamed: 0,imdb_title_id,original_title,year,date_published,genre,duration,country,language,director,actors,description,avg_vote,votes
1961,1961,tt0069049,The Other Side of the Wind,2018,2018-11-02,Drama,122,"France, Iran, USA","English, German",Orson Welles,"John Huston, Oja Kodar, Peter Bogdanovich, Sus...",A Hollywood director emerges from semi-exile w...,6.8,5887
6260,6260,tt0118926,The Dancer Upstairs,2002,2003-01-10,"Crime, Drama, Thriller",132,"Spain, USA","English, Quechua, Spanish",John Malkovich,"Javier Bardem, Juan Diego Botto, Laura Morante...",A police detective in a South American country...,6.9,6242
6440,6440,tt0120679,Frida,2002,2003-01-17,"Biography, Drama, Romance",123,"Mexico, USA, Canada","English, French, Russian",Julie Taymor,"Salma Hayek, Mía Maestro, Amelia Zapata, Aleja...",A biography of artist,7.4,79690
6441,6441,tt0120681,From Hell,2001,2001-12-21,"Horror, Mystery, Thriller",122,"USA, Czech Republic, UK",English,"Albert Hughes, Allen Hughes","Johnny Depp, Heather Graham, Ian Holm, Robbie ...","In Victorian-era London, a troubled clairvoyan...",6.8,144714
6452,6452,tt0120737,The Lord of the Rings: The Fellowship of the Ring,2001,2002-01-18,"Action, Adventure, Drama",178,"New Zealand, USA","English, Sindarin",Peter Jackson,"Alan Howard, Noel Appleby, Sean Astin, Sala Ba...",A meek Hobbit from the Shire and eight compani...,8.8,1619920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17567,17567,tt9894394,Upin & Ipin: Keris Siamang Tunggal,2019,2019-03-21,Animation,100,Malaysia,Malay,"Adam Bin Amiruddin, Syed Nurfaiz Khalid bin Sy...","Asyiela Putri Bt Azhar, Mohd Amir Asyraf Bin M...","Upin, Ipin and their friends come across a mys...",7.9,440
17568,17568,tt9894440,Min pappa Marianne,2020,2020-02-21,"Comedy, Drama",110,Sweden,Swedish,Mårten Klingberg,"Hedda Stiernstedt, Rolf Lassgård, Lena Endre, ...","After breaking up with her boyfriend, 28 year ...",7.2,545
17569,17569,tt9900060,Lupin the IIIrd: Mine Fujiko no Uso,2019,2019-05-31,"Animation, Adventure, Crime",58,Japan,Japanese,Takeshi Koike,"Kan'ichi Kurita, Kiyoshi Kobayashi, Miyuki Saw...",Fujiko befriends a young boy whose late father...,6.9,103
17570,17570,tt9911196,De Beentjes van Sint-Hildegard,2020,2020-02-13,"Comedy, Drama",103,Netherlands,"German, Dutch",Johan Nijenhuis,"Herman Finkers, Johanna ter Steege, Leonie ter...",A middle-aged veterinary surgeon believes his ...,7.7,724
17571,17571,tt9914942,La vida sense la Sara Amat,2019,2020-02-05,Drama,74,Spain,Catalan,Laura Jou,"Maria Morera Colomer, Biel Rossell Pelfort, Is...","Pep, a 13-year-old boy, is in love with a girl...",6.7,102

In [ ]:
new_df.to_csv